{{- $root := . -}}
{{- range $root_key, $root_value := .Values.values }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $root_key }}"
  namespace: "{{ $root.Values.kubernetesNamespace }}"
type: Opaque
data:
  {{- range $key, $value := $root_value }}
  {{ $key }}: {{ $value }}
  {{- end }}

{{- end }}