apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Values.kubernetesNamespace }}
  labels:
  {{- if eq .Values.serviceType "LoadBalancer"}}
    dns: route53
  {{- end}}    
    chart: "{{ .Values.serviceName }}-{{ .Values.serviceVersion | replace "+" "_" }}"
  {{- if or (eq .Values.serviceType "LoadBalancer") (eq .Values.serviceType "InternalLoadBalancer") }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.sslCertificate }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
    domainName: "{{ .Values.domainName }}"
    {{- if eq .Values.serviceType "InternalLoadBalancer"}}
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    {{- end}}
    {{- if .Values.route53ZoneIds}}
    route53ZoneIds: {{ .Values.route53ZoneIds }}
    {{- end}}
  {{- end}}
spec:
  {{- if or (eq .Values.serviceType "LoadBalancer") (eq .Values.serviceType "InternalLoadBalancer") }}
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - port: {{ .Values.serviceExternalPort }}
    targetPort: {{ .Values.serviceInternalPort }}
    protocol: {{ .Values.serviceProtocol }}
    name: {{ .Values.serviceName }}
  - port: 443
    targetPort: {{ .Values.serviceInternalPort }}
    protocol: {{ .Values.serviceProtocol }}
    name: "{{ .Values.serviceName }}-https"
  {{- else }}
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.serviceExternalPort }}
    targetPort: {{ .Values.serviceInternalPort }}
    protocol: {{ .Values.serviceProtocol }}
    name: {{ .Values.serviceName }}
  {{- end}}
  selector:
    app: {{ template "name" . }}
