GLOBAL_CONFIG_KEY_1: &GLOBAL_CONFIG_KEY_1 "GLOBAL_CONFIG_VALUE_1"
GLOBAL_CONFIG_KEY_2: &GLOBAL_CONFIG_KEY_2 "GLOBAL_CONFIG_VALUE_2"
GLOBAL_CONFIG_KEY_3: &GLOBAL_CONFIG_KEY_3 "GLOBAL_CONFIG_VALUE_3"

values:
  service1:
    GLOBAL_CONFIG_KEY_1: *GLOBAL_CONFIG_KEY_1
    SERVICE_1_SPECIFIC_CONFIG_KEY_1: &SERVICE_1_SPECIFIC_CONFIG_KEY_1 "SERVICE_1_SPECIFIC_CONFIG_VALUE_1"
    SERVICE_1_SPECIFIC_CONFIG_KEY_2: &SERVICE_1_SPECIFIC_CONFIG_KEY_2 "SERVICE_1_SPECIFIC_CONFIG_VALUE_2"
    SERVICE_1_SPECIFIC_CONFIG_KEY_3: &SERVICE_1_SPECIFIC_CONFIG_KEY_3 "SERVICE_1_SPECIFIC_CONFIG_VALUE_3"

  service2:
    GLOBAL_CONFIG_KEY_2: *GLOBAL_CONFIG_KEY_2
    SERVICE_2_SPECIFIC_CONFIG_KEY_1: &SERVICE_2_SPECIFIC_CONFIG_KEY_1 "SERVICE_2_SPECIFIC_CONFIG_VALUE_1"
    SERVICE_2_SPECIFIC_CONFIG_KEY_2: &SERVICE_2_SPECIFIC_CONFIG_KEY_2 "SERVICE_2_SPECIFIC_CONFIG_VALUE_2"
    SERVICE_2_SPECIFIC_CONFIG_KEY_3: &SERVICE_2_SPECIFIC_CONFIG_KEY_3 "SERVICE_2_SPECIFIC_CONFIG_VALUE_3"

  service3:
    GLOBAL_CONFIG_KEY_3: *GLOBAL_CONFIG_KEY_3
    SERVICE_3_SPECIFIC_CONFIG_KEY_1: &SERVICE_3_SPECIFIC_CONFIG_KEY_1 "SERVICE_3_SPECIFIC_CONFIG_VALUE_1"
    SERVICE_3_SPECIFIC_CONFIG_KEY_2: &SERVICE_3_SPECIFIC_CONFIG_KEY_2 "SERVICE_3_SPECIFIC_CONFIG_VALUE_2"
    SERVICE_3_SPECIFIC_CONFIG_KEY_3: &SERVICE_3_SPECIFIC_CONFIG_KEY_3 "SERVICE_3_SPECIFIC_CONFIG_VALUE_3"