{{- $root := . -}}
{{- range $root_key, $root_value := .Values.values }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $root_key }}"
  namespace: "{{ $root.Values.kubernetesNamespace }}"
data:
  {{- range $key, $value := $root_value }}
  {{ $key }}: {{ $value|quote }}
  {{- end }}

{{- end }}